core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from .views import robots
from products.sitemap import sitemaps

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('robots.txt', robots),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

products/forms.py
from django import forms


class ContactForm(forms.Form):
    your_name = forms.CharField(label='Ваше имя', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    your_number = forms.CharField(label='Ваш номер', max_length=100,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))

templates/blocks/menu.html
</div>
<div class="container-fluid px-0 py-1 mb-3 mycolor2">
    <div class="container">
        <nav class="navbar navbar-expand-lg ">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'ProductList' %}">Главная <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Contacts' %}">Контакты</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Delivery' %}">Доставка</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'Order' %}">Как купить</a>
                </li>

            </ul>
          </div>
        </nav>

    </div>
</div>
<div class="container">

templates/blocks/modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Заказать обратный звонок</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{% url 'email' %}">
          {% csrf_token %}
      <div class="modal-body">
          <label for="id_your_number">Ваше имя:</label>
          {{ FORM.your_name }}
          <label for="id_your_number">Ваш номер:</label>
          {{ FORM.your_number }}

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
          <input type="submit" class="btn btn-primary" value="Перезвоните мне">
      </div>
      </form>
    </div>
  </div>
</div>